name: Build

on: push

jobs:
  linux:
    name: Linux desktop
    runs-on: ubuntu-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0
        with:
          version: 5.15.2

      - name: Set up JSON
        uses: actions/checkout@v2
        with:
          repository: 'nlohmann/json'
          submodules: 'recursive'

      - name: Install JSON
        run: |
          mkdir build && cd build
          cmake -DJSON_BuildTests=OFF ..
          cmake --build .
          sudo cmake --install .
          cd ..

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
          cd ..

  windows:
    name: Windows desktop
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0
        with:
          version: 5.15.2

      - name: Set up JSON
        uses: actions/checkout@v2
        with:
          repository: 'nlohmann/json'
          submodules: 'recursive'

      - name: Install JSON
        run: |
          mkdir build && cd build
          cmake -DJSON_BuildTests=OFF ..
          cmake --build .
          cmake --install .
          cd ..

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
          cd ..

  macos:
    name: macOS desktop
    runs-on: macos-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0
        with:
          version: 5.15.2

      - name: Set up JSON
        uses: actions/checkout@v2
        with:
          repository: 'nlohmann/json'
          submodules: 'recursive'

      - name: Install JSON
        run: |
          mkdir build && cd build
          cmake -DJSON_BuildTests=OFF ..
          cmake --build .
          cmake --install .
          cd ..

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
          cd ..
