name: Linux build

on:
  push:
  workflow_dispatch:
    inputs:
      packageRelease:
        description: 'Package binaries for release and upload them'
        required: false
        default: false

jobs:
  linux:
    name: Linux desktop (Qt ${{ matrix.qt-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        qt-version: ['5.15.2', '6.1.2']

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt-version }}

      - name: Fetch JSON
        uses: actions/checkout@v2
        with:
          repository: 'nlohmann/json'
          submodules: 'recursive'

      - name: Install JSON
        run: |
          mkdir build && cd build
          cmake -DJSON_BuildTests=OFF ..
          cmake --build .
          sudo cmake --install .
          cd ..

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=MinSizeRel ..
          cmake --build .
          cd ..

      # now we can deploy the release if necessary
      - name: Install LinuxDeploy
        if: ${{ github.event.inputs.packageRelease }}
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt appimage
          dir: ${{ github.workspace }}

      - name: Build release package
        if: ${{ github.event.inputs.packageRelease }}
        run: |
          linuxdeploy-x86_64.AppImage --plugin qt --output appimage --desktop-file ClockifyTrayIcons.desktop --icon-file icons/ClockifyTrayIcons.svg --executable build/ClockifyTrayIcons --appdir AppDir

      - name: Upload release package
        if: ${{ github.event.inputs.packageRelease }}
        uses: actions/upload-artifact@v2
        with:
          name: Linux package (64-bit, Qt ${{ matrix.qt-version }})
          path: ClockifyTrayIcons-*-x86_64.AppImage
