name: macOS build

on: push
jobs:
  macos:
    name: macOS desktop (Qt ${{ matrix.qt-version }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        qt-version: ['5.15.2', '6.1.2']

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt-version }}

      - name: Fetch JSON
        uses: actions/checkout@v2
        with:
          repository: 'nlohmann/json'
          submodules: 'recursive'

      - name: Install JSON
        run: |
          mkdir build && cd build
          cmake -DJSON_BuildTests=OFF ..
          cmake --build .
          cmake --install .
          cd ..

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=MinSizeRel ..
          cmake --build .
          cd ..

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: macOS_Qt-${{ matrix.qt-version }}_binary
          path: build/ClockifyTrayIcons
