name: macOS build

on:
  push:
  workflow_dispatch:
    inputs:
      packageRelease:
        description: 'Package binaries for release and upload them'
        required: false
        default: ${{ startsWith(github.ref, "refs/tags/v") }}

jobs:
  macos:
    name: macOS desktop (Qt ${{ matrix.qt-version }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        qt-version: ['6.2.3', '6.3.0']

    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: qt-cache-${{ matrix.qt-version }}-${{ runner.os }}-version-2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt-version }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          modules: 'qtnetworkauth'
          aqtversion: "==2.1.*"
          # work around https://github.com/jurplel/install-qt-action/issues/142 as per https://github.com/jurplel/install-qt-action/issues/130
          setup-python: false

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
          cd ..

      # If Apple didn't insist on bundling apps as folders, this wouldn't be necessary; however, this is done to ensure that the .app folder remains intact
      - name: Prepare binary for uploading
        run: |
          mkdir upload_dir
          cd upload_dir
          cp -r ../build/TimeLight.app .
          cd ..

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: macOS binary (Qt ${{ matrix.qt-version }})
          path: upload_dir
          retention-days: 7

      - name: Build release package
        if: ${{ github.event.inputs.packageRelease }}
        run: |
          mkdir release_dir
          cd release_dir
          cp -r ../build/TimeLight.app .
          macdeployqt TimeLight.app -dmg
          cd ..

      - name: Upload release package
        if: ${{ github.event.inputs.packageRelease }}
        uses: actions/upload-artifact@v2
        with:
          name: macOS package (64-bit, Qt ${{ matrix.qt-version }})
          path: release_dir/TimeLight.dmg
          retention-days: 7
