name: Windows build

on:
  push:
  workflow_dispatch:
    inputs:
      packageRelease:
        description: 'Package binaries for release and upload them'
        required: false
        default: false

jobs:
  windows:
    name: Windows desktop (Qt ${{ matrix.qt-version }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        qt-version: ['6.2.3', '6.3.0']

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt-version }}

      - name: Install Qt IFW
        uses: jmarrec/setup-qtifw@v1.0.3
        with:
          qtifw-version: '4.x'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DGENERATE_INSTALLER=ON ..
          cmake --build . --config Release --target package
          cd ..

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: Windows binary (Qt ${{ matrix.qt-version }})
          path: build\Release\TimeLight.exe
          retention-days: 7

      - name: Build release package
        if: ${{ github.event.inputs.packageRelease }}
        # Windows deployments tend to be big, so we'll zip them before uploading
        run: |
          7z a -tzip TimeLight.zip build\Release\TimeLight-*-win*.exe

      - name: Upload release package
        if: ${{ github.event.inputs.packageRelease }}
        uses: actions/upload-artifact@v2
        with:
          name: Windows package (64-bit, Qt ${{ matrix.qt-version }})
          path: TimeLight.zip
          retention-days: 7
